version: "3"

services:
  app:
    container_name: app
    build: ./docker/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/var/www/html
      - ./logs/:/var/log/php
      - ./logs/:/var/log/laravel
      - ./logs/:/var/log/uptalk
      - ./logs/:/var/www/html/storage/logs
      - ./docker-configs/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - '$PWD:$PWD'

  nginx:
    image: nginx:1.20.1
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./server:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql/mysql-server:8.0
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uptalk
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025

  minio:
    image: minio/minio:latest
    container_name: 'minio'
    ports:
      - 9090:9000
      - 8900:8900
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    command: -c "
      mkdir -p /data/.minio.sys/buckets;
      cp -r /policies/* /data/.minio.sys/;
      cp -r /export/* /data/;
      minio server /data --console-address :8900"
    volumes:
      - ./docker/minio/data:/data
      - ./docker/minio/export:/export
      - ./docker/minio/policies:/policies
